# data
dataset: /data1/cenjianhuan/DFTDataset/NMC/nmc.txt
split_file: /data1/cenjianhuan/DFTDataset/NMC/split.json
batch: 8
# model
use_painn_model: True
num_interactions: 3
node_size: 128
load_model: None
ignore_pbc: False
force_pbc: False
# train
max_steps: 100000000
cutoff: 4
output_dir: ./results/nmc_painn
device_target: GPU
device_id: 2
mode: Pynative
